version: '3.8'

services:
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry

  impostos-microservice:
    build: ./impostos-microservice
    ports:
      - "8082:8082"
    depends_on:
      - service-registry

  registro-microservice:
    build: ./registro-microservice
    ports:
      - "8084:8084"
    depends_on:
      - service-registry