server:
  port: 8082

spring:
  application:
    name: impostos-microservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.vendas.impostos: DEBUG
