server:
  port: 8084

spring:
  application:
    name: registro-microservice

  datasource:
    url: jdbc:h2:mem:registro_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: registro-microservice

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    "[com.vendas.registro]": DEBUG
