server:
  port: 8082

spring:
  application:
    name: impostos-microservice

  datasource:
    url: jdbc:h2:mem:impostos_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: impostos-microservice

management:
  endpoints:
    web:
      exposure:
        include: health,info
