spring:
  application:
    name: vendas-monolito
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
  sql:
    init:
      mode: always
      platform: h2

datasource:
  url: jdbc:h2:mem:vendasdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password:

logging:
  level:
    org.hibernate.SQL: DEBUG
